name: CI
on: [ push ]

jobs:
  lint-and-test:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Run linter
        run: |
          shellcheck bin/*
          shellcheck -P SCRIPTDIR -x test/utils test/test-*

      - name: Run tests
        run: ./run_tests.sh
